---
title: "Oxygen Assessment Plots"
author: "Kate Collingridge"
date: "19/01/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(plotly)
library(plyr)
outputPath = file.path("Output_chl_weighted/oxy_plots")

```

This R markdown takes the outputs from the COMPEAT tool for dissolved oxygen and creates further plots to summarise the results

```{r read data}
wk3_COMP1 <- read.csv("Output_chl_weighted/1990-2000-HS1/Annual_Indicator.csv")
wk3_COMP2 <- read.csv("Output_chl_weighted/2001-2006-HS1/Annual_Indicator.csv")
wk3_COMP3 <- read.csv("Output_chl_weighted/2006-2014-HS1/Annual_Indicator.csv")
wk3_COMP4 <- read.csv("Output_chl_weighted/2015-2020-HS1/Annual_Indicator.csv")
wk3 <- rbind.fill(wk3_COMP1, wk3_COMP2, wk3_COMP3, wk3_COMP4)
wk3 <- merge(wk3, st_drop_geometry(units) %>% dplyr::select(UnitID, UnitCode = Code, UnitName = Description), by = c("UnitID"), all.x = TRUE)

indicatorID <- indicators[4, IndicatorID]
indicatorCode <- indicators[4, Code]
indicatorName <- indicators[4, Name]
indicatorUnit <- indicators[4, Units]
indicatorDepthMin <- indicators[4, DepthMin]
indicatorDepthMax <- indicators[4, DepthMax]
indicatorMetric <- indicators[4, Metric]


```


```{r trends}
#Plot of oxygen 5th percentile through time
for (u in unique(wk3$UnitCode)) {
  wk <- wk3[wk3$IndicatorID == 4 & wk3$UnitCode == u,]
  
  unitID <- st_drop_geometry(units)[Code == u]$UnitID
  unitCode <- u
  unitName <- st_drop_geometry(units)[Code == u]$Description
  
  title <- paste0("Eutrophication State [ES] and Threshold [ET] ", 1990, "-", 2020)
  subtitle <- paste0(indicatorName, " (", indicatorCode, ")", " in ", unitName, " (", unitCode, ")", "\n")
  subtitle <- paste0(subtitle, "Months: ", indicatorMonthMin, "-", indicatorMonthMax, ", ")
  subtitle <- paste0(subtitle, "Depths: ", indicatorDepthMin, "-", indicatorDepthMax, "m, ")
  subtitle <- paste0(subtitle, "Metric: ", indicatorMetric, ", ")
  subtitle <- paste0(subtitle, "Unit: ", indicatorUnit)
  
  fileName <- gsub(":", "", paste0("Annual_Indicator_Line_", indicatorCode, "_", unitCode, ".png"))
  
  ggplot(wk, aes(x = as.Date(as.character(Period), "%Y"), y = ES, group = UnitCode, color = UnitCode)) +
    labs(title = title , subtitle = subtitle) +
    geom_point() +
    geom_line() +
    #geom_text(aes(label = N), vjust = -0.25, hjust = -0.25) +
    #adding lines for boundaries between high/good/moderate etc
    geom_hline(aes(yintercept = ET)) +
    geom_hline(aes(yintercept = 7.75), linetype = 2) +
    geom_hline(aes(yintercept = 4.25), linetype = 2) +
    geom_hline(aes(yintercept = 2.5), linetype = 2) +
    #labelling high/good/moderate etc
    annotate("text", x = as.Date("2005", "%Y"), y = 5, label = "italic(Moderate)", parse = 2, size = 3.5, color = "grey") + 
    annotate("text", x = as.Date("2005", "%Y"), y = 6.75, label = "italic(Good)", parse = 2, size = 3.5, color = "grey") +
    annotate("text", x = as.Date("2005", "%Y"), y = 3.5, label = "italic(Poor)", parse = 2, size = 3.5, color = "grey") +
    annotate("text", x = as.Date("2005", "%Y"), y = 1.5, label = "italic(Bad)", parse = 2, size = 3.5, color = "grey") +
    annotate("text", x = as.Date("2005", "%Y"), y = 8.75, label = "italic(High)", parse = 2, size = 3.5, color = "grey") +
    scale_x_date(date_labels = "%Y") +
    xlab("Year") +
    ylab("Oxygen (mg/l)") +
    scale_y_continuous(limits = c(0,9), breaks = c(0,2,4,6,8))
  if (nrow(wk) >0) {
    ggsave(file.path(outputPath, fileName), width = 15, height = 9, dpi = 300)
    }
  
  
}

```

```{r mann kendall}
trends <- wk3[wk3$IndicatorID == 4,]
str(trends)
trends <- subset(trends,!is.na(trends$ES))
polygon <- trends$Code.x
polygon_nonnull <- !is.na(polygon)
polygon <- polygon[polygon_nonnull]
poly.names <- unique(trends$Code.x)

mkstat <- rep(-9999, length(poly.names))
mkp <- mkstat

for (j in poly.names) {
  #j=poly.names[2]
  trends_j <- trends[trends$Code.x==j,]
  trends_j <- trends_j[order(trends_j$UnitID,trends_j$Period),]
  trends_j <- trends_j[order(trends_j$UnitID),]
  temp <- mannkendall(trends_j$Period, trends_j$ES, nsims.mk=9999)
  mkstat[j] <- temp$mann
  mkp[j] <- temp$pvalue
  plot(trends_j$Period, trends_j$ES, main=j)
  tt <- lm(trends_j$ES ~ trends_j$Period)
  lines(trends_j$Period, tt$fitted.values)
}


mkstat[53:104]                               # Mann-Kendall statistic
mkp[53:104]                                 # p-values

table(polygon)                       # Number of years used


mk_results_oxy <- as.data.frame(table(polygon))
colnames(mk_results_oxy) <- c("Code","No_Years")
mk_results_oxy$mkstat <- mkstat[53:104]  
mk_results_oxy$mkp <- mkp[53:104]  

mk_results_oxy <- merge(st_drop_geometry(units[1:4]), mk_results_oxy, by = "Code")
fwrite(mk_results_oxy, file = file.path(outputPath, "mk_results_oxy.csv"))



#mann kendall for o2sat

wk1 <- read.csv("C:/Users/KC05/OneDrive - CEFAS/COMPEAT/Dissolved_oxygen/Output_chl_weighted/2015-2020/O2sat.csv")
wk1 <- as.data.table(wk1)
wk2 <- wk1[, .(ES = mean(ES), SD = sd(ES), N = .N, NM = uniqueN(Month)), keyby = .(IndicatorID, UnitID, Period)]
wk2 <- merge(st_drop_geometry(units[1:4]), wk2, by = "UnitID")

trends <- wk2[wk2$IndicatorID == 4,]
str(trends)
trends <- subset(trends,!is.na(trends$ES))
polygon <- trends$Code
polygon_nonnull <- !is.na(polygon)
polygon <- polygon[polygon_nonnull]
poly.names <- unique(trends$Code)

mkstat <- rep(-9999, length(poly.names))
mkp <- mkstat

for (j in poly.names) {
  #j=poly.names[2]
  trends_j <- trends[trends$Code==j,]
  trends_j <- trends_j[order(trends_j$UnitID,trends_j$Period),]
  trends_j <- trends_j[order(trends_j$UnitID),]
  temp <- mannkendall(trends_j$Period, trends_j$ES, nsims.mk=9999)
  mkstat[j] <- temp$mann
  mkp[j] <- temp$pvalue
  plot(trends_j$Period, trends_j$ES, main=j)
  tt <- lm(trends_j$ES ~ trends_j$Period)
  lines(trends_j$Period, tt$fitted.values)
}


mkstat[51:100]                               # Mann-Kendall statistic
mkp[51:100]                                 # p-values

table(polygon)                       # Number of years used


mk_results_oxy <- as.data.frame(table(polygon))
colnames(mk_results_oxy) <- c("Code","No_Years")
mk_results_oxy$mkstat <- mkstat[51:100]  
mk_results_oxy$mkp <- mkp[51:100]  

mk_results_oxy <- merge(st_drop_geometry(units[1:4]), mk_results_oxy, by = "Code")
fwrite(mk_results_oxy, file = file.path(outputPath, "mk_results_oxy_sat_mean.csv"))


```

```{r dataplot}
COMP4_areas <- sf::st_read("https://raw.githubusercontent.com/ices-tools-dev/COMPEAT/master/assessment_areas/COMP4_assessment_areas.csv") %>%
  st_set_crs(4326)

leaflet(COMP4_areas) %>%
  addTiles() %>%
  addPolygons(color = "black", fillOpacity = 0, weight = 1) %>%
  addCircles(data = wk1, ~Longitude, ~Latitude,) %>%
  #addCircles(data = filteredDataLIMS(), ~longitude, ~latitude, color = "green") %>%
  #addCircles(data = filteredDataEA(), ~Longitude, ~Latitude, color = "green") %>%
  addLegend(colors=c("blue"), labels=c("ICES COMPEAT data"))

```
